version: "3.9"

services:
  madeline:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - madeline-network
    restart:
      always

networks:
  madeline-network:
