version: "3.3"

services:
  madeline:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./gcp-key.json:/app/gcp-key.json
    networks:
      - madeline-network
    restart:
      always

networks:
  madeline-network:
