name: pre-commit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: runner / Pre-commit actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.10.x"
      - name: Setup annotations
        uses: PennyDreadfulMTG/setup-linters@main
      - name: Install Dependencies
        run: |
          pip install pre-commit isort
      - name: Run Isort
        continue-on-error: true
        run: |
          isort .
      - name: Run Pre-commit
        continue-on-error: true
        run: |
          pre-commit run --all-files
      - name: Commit Fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          commit_message: "[pre-commit] auto fixes"
          # Optional commit user and author settings
          commit_user_name: github-actions[bot] # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com> # defaults to author of the commit that triggered the run