name: precommit-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / Pre-commit actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.10.x'
      - name: Setup annotations
        uses: PennyDreadfulMTG/setup-linters@main
      - name: Install Pre-commit
        run: |
          pip install pre-commit
      - name: Run Pre-commit
        id: pre-commit
        continue-on-error: true
        run: |
          pre-commit run --all-files
      - name: Upload changes to Github (if exist)
        if: steps.pre-commit.result == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: pre-commit fixes"